### ISSUE TITLE
rerun CHILDES pipeline

### ISSUE THREAD

**Issue by mcfrank** [mikabr/aoa-prediction#6]

**Comment by mikabr** [comment]
I explored re-doing the pipeline in childesr, since that would have the benefits of 1) being more reproducible; 2) enabling us to add contextual diversity; 3) potentially improving frequency estimates and/or adding more languages. It would be more work than I thought, though, because only some languages have stem info in the db, so we'd need to pull in *all* tokens for each language, and do all the stemming stuff within R. It's doable but a fair bit of work. Is it worth it for these improvements? Do we have a good way of addressing the reviewer request for CD without it?
